Moving browser close to finally
crompco/html-to-pdf-puppeteer pull request #2
Opened 2023-08-16 12:27 UTC by gdecris

Moved the browser close statement out of the `try` and into the `finally` to ensure it is executed even if an error is encountered.

2023-08-16 12:46 UTC, gdecris commented
I can't get the binary to work with this change but might be something we should look at. Seems like the chrome process never exits.

2023-08-17 15:17 UTC, epixian requested changes

2023-08-17 15:17 UTC, epixian commented on pup.js
> +        await browser.close();
This will fail since `browser` is declared within the `try` block.

2023-08-21 14:54 UTC, gdecris commented
Updated PR to now also upgrade puppeteer.  Also fixed issue with declaration of the browser variable.

2023-08-21 15:16 UTC, merged